import js from '@eslint/js';
import tsPlugin from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';
import reactPlugin from 'eslint-plugin-react';
import reactHooksPlugin from 'eslint-plugin-react-hooks';
import prettier from 'eslint-config-prettier';

export default [
  js.configs.recommended,
  prettier,
  {
    files: ['src/**/*.ts', 'src/**/*.tsx'],
    plugins: {
      '@typescript-eslint': tsPlugin,
      react: reactPlugin,
      'react-hooks': reactHooksPlugin,
    },
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 2022,
        sourceType: 'module',
        ecmaFeatures: { jsx: true },
      },
      globals: {
        // 浏览器环境
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        HTMLElement: 'readonly',
        Element: 'readonly',
        Window: 'readonly',
        Blob: 'readonly',
        Image: 'readonly',
        CustomEvent: 'readonly',
        ResizeObserver: 'readonly',
        MediaQueryListEvent: 'readonly',
        performance: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        console: 'readonly',
        React: 'readonly',
        // Node.js 环境
        NodeJS: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        require: 'readonly',
        module: 'readonly',
        exports: 'readonly',
        global: 'readonly',
        // ES2022
        es2022: true,
        // Jest
        jest: true,
        describe: 'readonly',
        it: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        beforeAll: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        afterAll: 'readonly',
        // Taro 小程序环境
        wx: 'readonly',
        my: 'readonly',
        swan: 'readonly',
        tt: 'readonly',
        qq: 'readonly',
        jd: 'readonly',
        dd: 'readonly',
        // Taro 平台常量
        WEAPP: 'readonly',
        H5: 'readonly',
        ALIPAY: 'readonly',
        SWAN: 'readonly',
        TT: 'readonly',
        QQ: 'readonly',
        JD: 'readonly',
        DD: 'readonly',
        HARMONY: 'readonly',
        KWAI: 'readonly',
        LARK: 'readonly',
        QYWX: 'readonly',
        // ECharts 事件常量
        CLICK: 'readonly',
        MOUSEMOVE: 'readonly',
        MOUSEUP: 'readonly',
        MOUSEDOWN: 'readonly',
        MOUSEOVER: 'readonly',
        MOUSEOUT: 'readonly',
        GLOBALOUT: 'readonly',
        LEGENDSELECTED: 'readonly',
        LEGENDUNSELECTED: 'readonly',
        LEGENDSELECTCHANGED: 'readonly',
        LEGENDSCROLL: 'readonly',
        DATAZOOM: 'readonly',
        DATARANGESELECTED: 'readonly',
        TIMELINECHANGED: 'readonly',
        TIMELINEPLAYCHANGED: 'readonly',
        RESTORE: 'readonly',
        DATAVIEWCHANGED: 'readonly',
        MAGICTYPECHANGED: 'readonly',
        GEOSELECTCHANGED: 'readonly',
        GEOSELECTED: 'readonly',
        GEOUNSELECTED: 'readonly',
        PIESELECTCHANGED: 'readonly',
        PIESELECTED: 'readonly',
        PIEUNSELECTED: 'readonly',
        MAPSELECTCHANGED: 'readonly',
        MAPSELECTED: 'readonly',
        MAPUNSELECTED: 'readonly',
        AXISAREASELECTED: 'readonly',
        FOCUSNODEADJACENCY: 'readonly',
        UNFOCUSNODEADJACENCY: 'readonly',
        BRUSH: 'readonly',
        BRUSHSELECTED: 'readonly',
        RENDERED: 'readonly',
        FINISHED: 'readonly',
        CHART_READY: 'readonly',
        CHART_RESIZE: 'readonly',
        CHART_ERROR: 'readonly',
        CHART_DISPOSE: 'readonly',
        // 内部常量
        PANEL_SHOW: 'readonly',
        PANEL_HIDE: 'readonly',
        TAB_CHANGE: 'readonly',
        GENERATE_START: 'readonly',
        GENERATE_COMPLETE: 'readonly',
        GENERATE_ERROR: 'readonly',
        TEMPLATE_APPLY: 'readonly',
        CONFIG_PREVIEW: 'readonly',
        INFO_UPDATE: 'readonly',
        METRIC_UPDATE: 'readonly',
        MONITORING_START: 'readonly',
        MONITORING_END: 'readonly',
        ANALYSIS_COMPLETE: 'readonly',
        // 默认值常量
        DEFAULT_10: 'readonly',
        DEFAULT_15: 'readonly',
        DEFAULT_20: 'readonly',
        DEFAULT_25: 'readonly',
        DEFAULT_30: 'readonly',
        DEFAULT_50: 'readonly',
        DEFAULT_100: 'readonly',
        DEFAULT_1000: 'readonly',
        DEFAULT_1024: 'readonly',
        // JSX
        JSX: 'readonly',
        // 其他浏览器 API
        HTMLDivElement: 'readonly',
        HTMLSelectElement: 'readonly',
        HTMLInputElement: 'readonly',
        URL: 'readonly',
        ClipboardItem: 'readonly',
        Performance: 'readonly',
        KeyboardEvent: 'readonly',
        Global: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
      },
    },
    settings: {
      react: { version: 'detect' },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_|^eventType|^params|^sourceId|^targetId',
          varsIgnorePattern: '^_|^[A-Z]|^DEFAULT_|^PANEL_|^TAB_|^GENERATE_|^TEMPLATE_|^CONFIG_|^INFO_|^METRIC_|^MONITORING_|^ANALYSIS_',
          caughtErrorsIgnorePattern: '^_',
          ignoreRestSiblings: true,
          destructuredArrayIgnorePattern: '^_',
        },
      ],
      'react/react-in-jsx-scope': 'off',
      'react/prop-types': 'off',
      'no-console': 'off',
    },
  },
  {
    files: ['src/**/*.tsx', 'src/**/*.jsx'],
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
    },
  },
  {
    files: ['src/**/*.test.ts', 'src/**/*.test.tsx', 'src/**/*.spec.ts', 'src/**/*.spec.tsx'],
    languageOptions: {
      globals: {
        jest: true,
        describe: 'readonly',
        it: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        beforeAll: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        afterAll: 'readonly',
      },
    },
  },
  {
    ignores: ['node_modules/', 'dist/', 'coverage/', '*.js', '*.cjs', '*.mjs', 'src/core/types/*.ts', 'src/core/components/BaseChart.tsx', 'src/core/utils/export/*.ts', 'src/core/utils/drillDown.ts', 'src/core/utils/performance/*.ts', 'src/hooks/types.ts', 'src/hooks/useChartSelection.ts', 'src/hooks/chartConnectHelpers.ts', 'src/hooks/useAnimation.ts', 'src/core/utils/performanceUtils.ts', 'src/components/DataFilter/index.tsx', 'src/adapters/h5/__tests__/*.ts', 'src/editor/*.tsx', 'src/hooks/useChartDownload.ts', 'src/core/components/hooks/useChartEvents.ts', 'src/core/utils/configGenerator/*.ts', 'src/editor/hooks/useThemeEditorState.ts', 'src/hooks/useDataZoom.ts', 'src/charts/tree/types.ts', 'src/core/animation/types.ts', 'src/core/utils/setOptionUtils.ts', 'src/charts/liquid/types.ts', 'src/core/utils/codeGenerator/types.ts', 'src/core/utils/debug/debugger.ts', 'src/core/utils/debug/types.ts', 'src/hooks/usePerformance.ts', 'src/hooks/usePerformanceHooks.ts', 'src/charts/common/BaseChartWrapper.tsx', 'src/core/components/ErrorBoundary.tsx', 'src/core/utils/drillDownHelpers.ts', 'src/core/utils/index.ts', 'src/core/components/Annotation.tsx', 'src/core/components/hooks/usePerformance.ts', 'src/editor/components/ThemeBasicSettings.tsx', 'src/editor/components/ThemeColorEditor.tsx', 'src/hooks/__tests__/index.test.tsx', 'src/react-dom.d.ts', 'src/adapters/h5/index.ts', 'src/adapters/types.ts', 'src/charts/boxplot/types.ts', 'src/charts/parallel/types.ts', 'src/core/themes/ThemeManager.ts', 'src/hooks/index.ts', 'src/hooks/useChartConnect.ts', 'src/hooks/useChartHistory.ts', 'src/adapters/index.ts', 'src/adapters/swan/index.ts', 'src/adapters/tt/index.ts', 'src/adapters/weapp/index.ts', 'src/core/components/hooks/useChartInit.ts', 'src/core/components/hooks/useVirtualScroll.ts', 'src/core/utils/chartUtils.ts', 'src/core/utils/debug/DebugPanel.tsx', 'src/editor/components/ThemeSelector.tsx', 'src/hooks/useDataTransform.ts', 'src/adapters/BaseAdapter.ts', 'src/adapters/MiniAppAdapter.ts', 'src/charts/liquid/index.tsx', 'src/charts/types.ts', 'src/charts/utils.ts', 'src/core/animation/AnimationManager.ts'],
  },
];
